### ISSUE TITLE
Rückseite Ersti-Info

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Ersti-Info#11]
Hier müsste das aktuelle Fest-Plakat hin, sofern es schon existiert, oder ein altes recycled werden.

**Comment by joker234** [comment]
Das Plakat wird in „druck“ abgeschnitten. Außerdem fehlt das RGB-Bild immer noch.

**Comment by joker234** [comment]
Der Issue ist nicht gefixed.

**Comment by joker234** [comment]
closed, weil für nächstes Jahr
