### ISSUE TITLE
Bilder Prüfungssekretariate einfügen

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Ersti-Info#111]
Im Rahmen von #110 könnte man sich überlegen, auch von den Prüfungssekretariaten Bilder einzufügen. In der Physik müsste man die allerdings vermutlich selber machen.

**Comment by TomTomRixRix** [comment]
Auch wenn unsere Prüfungssekretärinnen bestimmt die häufigsten Anlaufstellen für Studis sind, finde ich es nicht so sinnvoll, Bilder von den Personen im Ersti Info abzudrucken. Wenn sie sich wie im Tagespropheten bewegen würden, dann vielleicht, aber so statische Bilder haben finde ich keinen Mehrwert. Wenn man das Prüfungssekretariat besucht, ist es einem ja normalerweise egal, wer einem dort weiterhilft, wie die Person aussieht etc., sondern man sucht einfach den Raum. Bei Dozenteninnen/Dekaninnen ist das vielleicht anders, weil da auch eine Interaktion stattfindet, die über eine pure Serviceleistung hinausgeht.

Abgesehen von dem inhaltlichen Argument bleibt das Problem, dass man erst einmal Bilder von den vier Personen bräuchte.
