### ISSUE TITLE
Vorlesungstitel kanonisieren

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#124]
z.B.
- Num0, Numerik 0, Einführung in die Numerik, Einführung in die numerische Mathematik
- Info1, IPI, Einführung in die Praktische Informatik

**Comment by friedz** [comment]
ich wäre dafür auf jeden Fall einmal mindestens den vollen Namen zu nennen dann im Text aber eine kanonische Abkürzung benutzen

also z.B. Einführung in die Numerik (Num0) [...] Num0 [...]

**Comment by imntl** [comment]
Wir sollten alle Benennungen als command im Fließtext einbinden (so wie Name des Dekans und anderer wichtiger Positionen) und diese in zu_aktualisieren legen, als eigene Datei, in der die Namen der Vorlesungen geregelt werden.

**Comment by flugdrachen** [comment]
So oft kommen die Vorlesungsnamen gar nicht im Text vor, im Prinzip nur in den Studiengangsbeschreibungen und in dem Abschnitt über Vorlesungen generell.

Was ich mich noch frage: ist es sinnvoller mit 1, 2, ... zu zählen oder mit I, II, ... ?
Ersteres wird in den Modulhandbüchern von Info und Mathe gemacht, die Physik verwendet aber römische Zahlen. 
Hat da jemand eine Meinung dazu?

**Comment by joker234** [comment]
Ohne nachzuschauen: die Fakultät ist hierbei auch sehr inkonsistent, sagt zumindest meine Jahrelange Erfahrung. Die Intention damals war, dass man im Ersti-Info einheitlich ist. Es ging auch weniger um die 1, 2, … oder I, II, …. Das finde ich eher egal, solange das Ersti-Info dabei in sich konsistent ist.

Was eher verwirrend für die Studis sein wird sind gerade die Beispiele die im ursprünglichen Beitrag benannt werden:
> * Num0, Numerik 0, Einführung in die Numerik, Einführung in die numerische Mathematik
> * Info1, IPI, Einführung in die Praktische Informatik
