### ISSUE TITLE
AP und FP ins Glossar

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#128]
Erläuterungen zu den Abkürzungen AP und FP gehören ins Glossar und nicht in die Fußnoten

https://github.com/FachschaftMathPhys/Ersti-Info/blob/95ff9c5fea1dbb9a6eb130a29f43c30bb4081db3/wie-geht-studium/praktikum.tex#L6 ff

**Comment by flugdrachen** [comment]
Aber Vorlesungsabkürzungen tauchen (bisher zumindest) ja auch nicht im Glossar auf... 
Wäre das denn sinnvoll?

**Comment by flugdrachen** [comment]
Eigentlich fällt das denke ich eher in #124
