### ISSUE TITLE
LP/CP/Credits vereinheitlichen

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Ersti-Info#13]
Momentan benutzen wir hier alle möglichen Begriffe für ein und die selbe Sache. Dass das das gleiche ist, kann man irgendwo mal anmerken, aber generell wäre es schön, das einheitlich zu haben.

**Comment by joker234** [comment]
was hätten wir denn gern? CP? LP? eigentlich wäre LP ja richtig.
