### ISSUE TITLE
Doppelter Strich vor Fußnoten hässlich

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#133]
![](https://joker234.de/share/bc0bc2b3/h%C3%A4sslich.png)
unten

**Comment by koebi** [comment]
Das ist nicht wirklich ein doppelter Strich, das ist ein Kapitel-Trennstrich und der Footnote-Strich. Das lässt sich am besten durch mehr (oder weniger) Inhalt und ergo eine Verschiebung der Texte fixen.
