### ISSUE TITLE
Weitere Informationsangebote für FÜK im 50%-Bachelor

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Ersti-Info#14]
Folgende Anmerkung kam von Gloria:

Desweiteren finde ich den allgemeinen Teil mit den FÜK im Lehramt noch 
relativ unklar, tatsächlich ist es ja auch unklar, weil wir da ja auch 
noch wenig Infos haben. Wäre es möglich, dass wir konkreter auf eine 
Stelle verweisen wo das später nachzulesen ist, sobald mehr Infos 
vorliegen? Möglicherweise könnte man ankündigen dass das zu einem 
späteren Zeitpunkt auf der Website der FS kundgetan wird. Vielleicht 
indem eine Rubrik "News aus dem 50%-Bachelor" oder "News aus dem neuen 
Lehramt" auf die Homepage setzen? Oder eine Mailingliste für die 
50%-Bacheloranten angeben auf die man sich eintragen kann. Gerade wenn 
Leute so etwas unvollständiges studieren wäre es vllt ganz schön ihnen 
da das Gefühl von Betreuung zu geben.

**Comment by joker234** [comment]
ich lese da nicht konkret raus, was wir dort jetzt tun sollen. So wie ich das sehe gibt's noch nichts was man da *jetzt* machen könnte.

**Comment by joker234** [comment]
was ist damit?
