### ISSUE TITLE
Free stuff für Studis

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhys/Ersti-Info#149]
es gibt haufenweise das $Firmen die kostenlose und coole Dinge, oder massiv Rabatt für Studis haben die HS Karlsruhe hat so stuff in ihrem Ersti-Info wir könnten das auch tun

**Comment by joker234** [comment]
prinzipiell ne gute Idee. Muss man sich halt überlegen was man da rein packen will. Die Fachschaft will evtl. nicht jede Firma da drin stehen haben. Gleichzeitig sollte man halt alle Firmen ähnlich behandeln.

**Comment by flugdrachen** [comment]
An sich gute Idee, aber ich denke, das umzusetzen funktioniert leider nicht so gut, weil man dann nachvollziehbare und transparente Kriterien bräuchte, nach denen man die Firmen auswählt.

**Comment by flugdrachen** [comment]
Wurde beim FSWE diskutiert.
