### ISSUE TITLE
Zeilenumbrüche

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhys/Ersti-Info#150]
So wie es derzeit umgebrochen ist ist es nicht möglich Änderungen in einem Diff genauer als auf den Absatz fest zu stellen.

Außerdem ist es Quasi unmöglich die Texte hier auf GitHub direkt zu lesen.

Besser zu lesen und praktischer für Diffe wäre ein Zeilenumbruch nach jedem Satz.

**Comment by imntl** [comment]
Ich kann mich daran erinnern, dass ich zusammen mit Johannes die derzeitigen Umbrüche erstellt haben, da mit damit besser mergen kann und damit besser simultan am Ersti-Info gearbeitet werden kann.
Ebenfalls sehe ich nicht, dass man die Diffs dann besser lesen kann, da neue und entfernte Wörte stärker in Farbe hinterlegt werden. Meiner Meinung nach ist die Lesbarkeit der Diffs im aktuellen Zustand sogar besser.

**Comment by friedz** [comment]
bei der Lesbarkeit der Diffs bin ich mir nicht sicher möglicherweise ist das in beiden Varianten mehr oder weniger gleich aber in der aktuellen Form ist es quasi unmöglich die Dateien auf GitHub direkt zu lesen da hier Zeilen nicht umgebrochen wenn sie zu lang sind

**Comment by joker234** [comment]
> So wie es derzeit umgebrochen ist ist es nicht möglich Änderungen in einem Diff genauer als auf den Absatz fest zu stellen.
Das sollte (eigentlich) nicht der Fall sein. Normalerweise sollten die nochmal stärker hervorgehoben werden.

> Außerdem ist es Quasi unmöglich die Texte hier auf GitHub direkt zu lesen.
da stimme ich dir zu.

> Besser zu lesen und praktischer für Diffe wäre ein Zeilenumbruch nach jedem Satz.￼￼ 
Hmm. Klingt anstrengend. Sieht halt echt nicht schön aus und macht es echt unschön zu lesen ¯\_(ツ)_/¯

**Comment by friedz** [comment]
das *sieht nicht schön aus* und macht es *unschön zu lesen* Argument ist ziemlich unsinnig wenn wir es mal mit dem aktuellen zustand vergleicht

**Comment by friedz** [comment]
So wie es gerade ist sind ja nicht einmal die *diffs*  schön zu lesen. Das einzige das es erreicht ist das es nicht versehentliche dazu kommt das im *diff* Dinge angezeigt werden die nur ein neuer Umbruch aber keine *echte* Änderung sind
![diff](https://user-images.githubusercontent.com/2459232/27004573-520f0d9a-4e0b-11e7-8f6d-735328518c1b.png)

**Comment by imntl** [comment]
Nach dem jetzigen Verfahern, wie wir mit Änderungen und PRs umgehen ist die Art und Weise wie Umgebrochen wird unserer Meinung nach die beste.

**Comment by joker234** [comment]
@friedz ich empfehle die folgenden zwei anderen diff Methoden die in meiner `.gitconfig` stehen: `cdiff` und `wdiff`. `vdiff` nutze ich selten, ist aber manchmal auch praktisch.

```
[alias]
	cdiff = diff --word-diff-regex=.
	vdiff = "difftool -y -x vimdiff"
	wdiff = diff --word-diff
```
