### ISSUE TITLE
Information zu Auslandssemester

### ISSUE THREAD

**Issue by voiter** [FachschaftMathPhys/Ersti-Info#155]
Information, dass es die Möglichkeit gibt Urlaubssemester zu nehmen und was es ist und was passiert, usw.

**Comment by friedz** [comment]
hättest du Lust eine Text zu schreiben in dem du Erstmal die Eckdaten und wichtigen Infos nennst das sauber zu formulieren und zu strukturieren können wir dann im Anschluss machen aber das es schon mal einen Text gibt von dem wir ausgehen können

**Comment by voiter** [comment]
Kann ich machen. Wird aber einige Zeit dauern bis alles komplett ist.

**Comment by friedz** [comment]
schreib einen Draft auf einem extra Branche dann können wir Dinge dazu sagen und vielleicht was anpassen sobald irgend was da ist
