### ISSUE TITLE
PDF Metadaten Inhaltsverzeichnis

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhys/Ersti-Info#156]
zur zeit ist kein Inhaltsverzeichnis in den PDF Metadaten, dadurch können PDF Viewer nicht die einzelnen Kapitel usw als eigenes weiteres Inhaltsverzeichnis anzeigen.

**Comment by TomTomRixRix** [comment]
Ich habe den Grund für das Fehlen der ToC Metadaten herausgefunden: Das Inhaltsverzeichnis geht beim Mergen vom Mantelbogen mit dem Inhaltsteil durch pdftk verloren. 

Das könnte man fixen, indem man sich die Metadaten des Inhaltsteils ausgeben lässt 
```
pdftk ersti.pdf dump_data output metadaten.txt
```
und diese dann später dem zusammengefügten Dokument wieder hinzufügt:
```
pdftk webseite.pdf update_info metadaten.txt output website_mit_toc.pdf
```

Allerdings verschieben sich natürlich durch das Mergen die Sprungmarken um zwei Seiten. Dementsprechend müsste man in `metadaten.txt` die Zahlen hinter `BookmarkPageNumber` um 2 inkrementieren. Ich habe dafür ein kleines Python Skript geschrieben.

```python
'''
Mit diesem Skript wird eine pdftk data_dump Datei bearbeitet, sodass die Bookmark Eintraege des Inhaltsverzeichnisses um zwei erhoeht werden. Dies ist notwendig, weil beim mergen des Mantelbogens mit dem Inhalt zwei zusaetzliche Seiten vorne angehaengt werden.
'''

with open('metadata.txt') as file:
    with open('metadata_new.txt','a') as outfile:
        line = file.readline()
        while line:
            if 'BookmarkPageNumber' in line:
                for sub in line.split():
                    if sub.isdigit():
                        pagenumber = int(sub)
                        line = line.replace(sub,str(pagenumber+2))
                        outfile.write(line)
            else:
                outfile.write(line)
            line = file.readline()
file.close()
```

Das geht bestimmt noch schöner, mit Kommandozeilenargumenten, aber als erster QuickFix wäre das meine Lösung. Langfristig sollte man das natürlich dann in das makefile integrieren. Vielleicht kann pdftk das updaten der Metadaten auch selber machen, da kenne ich mich leider nicht aus. Wenn jemand eine schönere Lösung kennt, würde ich mich freuen, sie hier zu lesen.
