### ISSUE TITLE
Kapitel Hochschulpolitik

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#161]
Das Kapitel zu Hochschulpolitik ist nicht sher gut lesbar oder verständlich und sollte deswegen überarbeitet werden.

**Comment by TomTomRixRix** [comment]
@flugdrachen und @imntl Was meint ihr: Soll ich den HoPo Text ganz von vorne nochmal neu schreiben, oder versuchen, den alten Text zu übernehmen und an vielen Stellen Verbesserungen zu machen?

Wenn ich den Text neu schreibe, würde ich ihn eher aus Sicht eines normalen Studis schreiben, sodass die Lesenden sehen, wo die HoPo auf sie trifft. Und dann würde die das ganze Konstrukt von unten her aufbauen, sodass ich über Studienkommission, Fakultät(-srat), Senat + Uni-Gremien zum LGH und der allgemeinen Politik komme. Dann können die Lesenden dort aussteigen, wo es sie nicht mehr interessiert ;)
