### ISSUE TITLE
CP vs LP

### ISSUE THREAD

**Issue by imntl** [FachschaftMathPhys/Ersti-Info#162]
Es gibt mehrere Stellen, an denen CP stehen und an anderen wiederum LP. Dies sollten wir ändern.

Es wird überall wo LP steht CP hingeschrieben und im Glossar bei CP geschrieben, dass diese auch LP heißen können.

**Comment by joker234** [comment]
Ich will euch ja da nicht unnötig reinreden, aber wir haben mal entschieden dass wir überall LP statt CP schreiben. Siehe u.a. diesen Commit https://github.com/FachschaftMathPhys/Ersti-Info/commit/5ca106115be8336e3f29a691edd77147ffebd7ec.

Wer sich mal irgendeine Prüfungsordnung anschaut wird feststellen, dass LP das deutsche Wort ist und dort exklusiv vorkommt (vgl. z.B. https://www.mathematik.uni-heidelberg.de/2015/PO-BSc.pdf). CP ist die englische Übersetzung. Man sollte also LP verwenden um unnötige Verwirrungen vorzubeugen. Wir haben uns damals durchaus was dabei gedacht.

**Comment by imntl** [comment]
Das haben wir leider nicht bedacht. Dann lassen wir das offensichtlich so wie es ist. Vielen Dank!

**Comment by friedz** [comment]
sollte das dann nun nicht einheitlich zu **LP** statt **CP** geändert werden?

**Comment by flugdrachen** [comment]
Stimmt, an zwei Stellen steht noch CP. Das sollte natürlich geändert werden.
