### ISSUE TITLE
Studentischer Arbeitsraum

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#166]
Im Kapitel "An der Uni" gibt es einen Artikel zum studentischen Arbeitsraum, der aktualisiert werden muss.

**Comment by ChrisBtt** [comment]
Nils Klughammer hat eine Mail mit der Bitte um Infos erhalten - Antwort steht aus

**Comment by friedz** [comment]
wenn das angepasst wird kann auch gleich #182 bearbeitet werden
