### ISSUE TITLE
Überflüssige Dateien, z. B. im Ordner wie-geht-studium

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#176]
Wenn ich das richtig sehe, werden die Dateien "was_ist_eine_uebungsgruppe.tex" und "lehrveranstaltungen.tex" gar nicht verwendet und überschneiden sich inhaltlich und wortwörtlich mit den tatsächlich verwendeten Dateien.
Kann man sie also einfach löschen?

Eventuell ist das auch noch in anderen Ordnern so, das muss man mal nachschauen.

**Comment by flugdrachen** [comment]
Von den anderen Dateien fehlen keine ganz, einzig "mathphys/volleyball.tex" ist in der ersti.tex auskommentiert.

**Comment by friedz** [comment]
Da wir das Volleyball Turnier nicht mehr machen sollte der Text nicht mehr vorkommen kann also eigentlich gelöscht werden wir können ihn ja falls er wieder gebraucht wird wieder holen das ist ja in einem Git :wink:

bei den Anderen Texten gehe ich auch davon aus das sie gelöscht werden können ein revert zu der Aktuellen oder früheren Versionen ist ja immer möglich
