### ISSUE TITLE
Vorkurspläne aktualisieren

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#178]
Sobald Zeiten und Daten zum Vorkurs sicher feststehen, sollten die "vorkursplan"-Dateien (in zu_aktualisieren) aktualisiert werden.

**Comment by friedz** [comment]
wir haben öfter überlegt die Vorkurspläne leer zu lassen oder nicht auf zu nehmen da sie eigentlich nie wirklich stimmten da sich immer etwas geändert hat oder zum Redaktionsschluss noch nicht fest standen

Wir könnten vielleicht einfach einen Blanko Plan einfügen den sich alle selbst eintragen können/müssen

**Comment by flugdrachen** [comment]
Die Zeitpläne, die da mal drin waren, sind das ja gar nicht mehr, sondern kurze Texte, in denen der Zeitraum und die groben Eckdaten des Vorkurses stehen und z. B. wo die Begrüßung ganz am Anfang stattfindet, was ja nicht ganz unwichtig ist.

Blanko-Plan fände ich aber trotzdem gut.

**Comment by flugdrachen** [comment]
Hmm, wobei die Ersti-Infos ja hauptsächlich dann erst bei der Begrüßung verteilt werden.
