### ISSUE TITLE
"Wir" bezieht sich nicht überall auf die Fachschaft

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhys/Ersti-Info#184]
Im Upstream text bezieht sich *wir* auf Upstream und nicht wie sonst überall auf die Fachschaft dass sollte  vielleicht angepasst werden

**Comment by friedz** [comment]
im Nigthline Text ist das genau so

**Comment by flugdrachen** [comment]
Finde ich aber eigentlich nicht so schlimm, so fühlt man sich als Leser eher angesprochen und traut sich viel eher, sich bei Upstream zu bewerben oder bei der Nightline anzurufen.
Vielleicht könnte man dann aber einen Hinweis dazu machen, dass das ein Infotext von Upstream/der Nightline ist, der nicht von uns selbst kommt?

**Comment by samuscherer** [comment]
Stimme da @flugdrachen zu, finde das auch nicht so schlimm. Da der gesamte Abschnitt auch mit "Weitere Angebote" vom Rest getrennt wird, ist es in meinen Augen auch klar ersichtlich, dass damit nicht die FS gemeint ist.

**Comment by friedz** [comment]
der Text passt aber auch sonst nicht 100% zum Rest und würde mindest in #21 zum generischen femininum angepasst werden müssen, aber ja im Allgemeinen können wir *(Hihi)* das ruhig so lassen

**Comment by samuscherer** [comment]
Wurde denn eimal das gesamte Ersti-Info vollständig gegendert? (Im Hinblick auf #21)

**Comment by flugdrachen** [comment]
Das passiert zur Zeit noch

**Comment by flugdrachen** [comment]
Also: Ist nicht so schlimm, da eh klar ist, dass der Text nicht aus unserer Sicht ist.
