### ISSUE TITLE
(Pro-) Seminare und Anfängerpraktikum

### ISSUE THREAD

**Issue by imntl** [FachschaftMathPhys/Ersti-Info#192]
Es sollte vielleicht eine Absatz geben, in dem erklärt wird, wie man an (Pro-)Seminare und Praktikas in der in Info kommt.

**Comment by imntl** [comment]
Mittlerweile ist ein Text geschrieben für (Pro-)Seminare (PR #215), jedoch fehlt immer noch ein Text für Praktika.

**Comment by OccamsBeard** [comment]
Das ist kein immanentes Thema für Erstis, weil die im ersten Semester in der Regel keine S/PS machen. die Idee ist jetzt, darauf hinzuweisen, dass das auf der (geplant) Ende August online gehenden neuen Website nachzulesen sein wird.
