### ISSUE TITLE
Öffnungszeiten Gebäude

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#198]
Es wäre cool, wenn es eine kuze Übersicht gibt wann man wo zum Zettelrechnen hinkann, also die Öffnungszeiten von Mathematikon, KIP, evtl. INF 252 und was sonst noch sinnvoll ist.

**Comment by imntl** [comment]
Das ist keine schlechte Idee. Die Öffnungszeiten sollten dann bitte aber auch als Command in zu_aktualisieren untergebracht werden, damit man jedes Jahr aufs neue darauf hingewiesen wird, dass man die aktualisieren sollte, falls sie sich geändert haben.

**Comment by TomTomRixRix** [comment]
Vorhin im AK kam auf, dass es vielleicht sinnvoller wäre, einfach zu erwähnen, wann man wo gut Zettelrechnen kann und dass man an manchen Orten auch noch drinnen weiterrechnen darf, auch wenn die Türen von außen nicht mehr zu öffnen sind. So spart man sich das regelmäßige updaten der Öffnungszeiten, die man als Studi ja ohnehin durch einfaches googlen herausfinden kann. Es wäre natürlich eine Ehre, wenn Studis dafür extra ins Ersti-Info schauen, aber das tut vermutlich niemand.
