### ISSUE TITLE
LICENSE erstellen

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#2]

**Comment by joker234** [comment]
wann passiert das?

**Comment by koebi** [comment]
Meine Argumentation für diese Lizenz wäre: 
Namensnennung wollen wir auf jeden Fall, Weitergabe unter gleichen Bedingungen dann auch. Ich bezweifle aber, dass wir rechtlich gegen eine tatsächliche Kommerzielle Nutzung vorgehen würden, daher würde ich dagegen verzichten.
