### ISSUE TITLE
QR-Codes im Vorkurs-Kapitel könnten hübscher sein

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#209]
Ich verstehe nicht ganz, wie die vertikale Position der QR-Codes bestimmt wird. So wie es jetzt ist ist aber nichts mit irgendwas auf einer Höhe. 
Ich fände es ganz schön, wenn der obere (oder der untere) Rand des Codes auf einer Höhe mit einem Absatzanfang oder zumindest einer Textzeile wäre. 

Außerdem wirken die QR-Codes ziemlich groß. Kann man hier auch \marginQRsmall verwenden?
Das ist aber vielleicht auch nur mein persönlicher Geschmack.

**Comment by imntl** [comment]
Das ist wohl richtig.
Leider konnte ich vor der letzten Herausgabe des Ersti-Infos nicht so ganz verstehen, warum die QR-Codes nicht horizontal an der gleichen Stelle sind. Wer mehr Ideen dazu hat darf sich gerne melden ;)

**Comment by flugdrachen** [comment]
Sollen entfernt werden

**Comment by TomTomRixRix** [comment]
Ist mit commit 30bc27d0f504bec3d9f3c989a3814cfe6e7465d5 behoben worden, muss also nur noch in den master gemerged werden

**Comment by flugdrachen** [comment]
fixed via #264
