### ISSUE TITLE
Gendern

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#21]
Wenn schon gendern, dann bitte konsistent. Z.B. wird auf Seite 2 und 16 (in vorschau_inhalt.pdf) unterschiedlich gegendert. Das muss noch korrigiert werden!

**Comment by friedz** [comment]
Worte wie jeder lassen sich offensichtlich nicht mit Binnen-I gendern ist uns das an der stelle dann völlig egal? oder sollte lieber alles noch einmal neu gegendert werden?

**Comment by joker234** [comment]
@friedz hast du nen Beispiel (gerne mit Zeilenlink hier in github). Dann kann ich mir was drunter vorstellen

**Comment by friedz** [comment]
Ok @joker234 z.B. in dem [MafIn](https://github.com/FachschaftMathPhys/Ersti-Info/blob/0ea4e7f406399824ec746e4f372a9eca9e9228e4/wie-geht-studium/mafin.tex#L12) Text

**Comment by friedz** [comment]
wie sollen wir den nun gendern? Ich kann mir sicher mal die Arbeit machen alles durch zu gehen, aber dafür muss ich wissen wie nun gegendert werden soll.

**Comment by imntl** [comment]
Was wäre denn eine sinnvolle Art zu gendern?

**Comment by friedz** [comment]
bin mir nicht ganz sicher eins von **\* ~ _ :** 

also:
+ *jede\*r* *Profesor\*in* usw
+ *jede~r* *Profesor~in* usw
+ *jede_r* *Profesor_in* ...
+ *jede:r* *Profesor:in* ...

Ich würde zu **:** tendieren, aber außer **_** find ich alles ok

**Comment by joker234** [comment]
> - jede:r Profesor:in ...

wtf, noch nie gesehen

> Was wäre denn eine sinnvolle Art zu gendern?

Eine „sinnvolle“ Art gibt es nicht. Nur eine am wenigsten schlechte. Gender mal einen Text und versuch ihn zu lesen. Dann weißt du was am wenigsten ätzend ist.

**Comment by friedz** [comment]
List an nicht Komplett Genderneutralen Artikeln die über arbeitet werden sollten:
- [ ] zu_aktualisieren
  - [x] vorkursplan.info.tex
  - [ ] vorkursplan.physik.tex

**Comment by friedz** [comment]
Der AK hat nun entschieden im gesamten Ersti-Info das generische femininum zu verwenden

**Comment by friedz** [comment]
*Studentenwerk* sollte auch zu *Studierendenwerk* geändert werden
