### ISSUE TITLE
Rückseite des Umschlags

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#218]
Gibt es schon ein Festplakat?

**Comment by TomTomRixRix** [comment]
Ja, ich weiß nicht genau, ob der AK Fest da noch etwas dran ändern will, weil ich heute nicht im AK war, aber man könnte da nochmal eine Mail schreiben an akfest@
Jedenfalls will der AK Fest auch ein Plakat an das Studierendenwerk senden für die Campus Zeitschrift, sodass sie eh eine vorläufige Version veröffentlichen müssen.
Hier liegt die aktuelle Version: https://mathphys.fsk.uni-heidelberg.de/svn/sumpf/fest/plakate/plakat_ws2017.png
