### ISSUE TITLE
Vorkursplan prominenter

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#22]
Ich hätte gern den Link auf den Vorkursplan prominenter platziert. Mir schwebte gerade sowas vor wie in weiß in das grüne der „2 Vorkurs“  Überschrift „http://mathphys.info/vorkurs/plan“ zu schreiben. Vielleicht gibts aber auch bessere Ideen.

**Comment by koebi** [comment]
Also, wenn dann in Schwarz ;) und will man da 'ne url reinschreiben? oder einfach 'ne footnote, oder über den Text 'nen Disclaimer?

**Comment by joker234** [comment]
ne footnote existiert doch schon. Die haben gefühlt wenige gelesen.

**Comment by koebi** [comment]
Ja, aber wenn man die Überschrift mit 'ner Footnote versieht? Alternativ kann man direkt dadrunter einen Disclaimer machen, vllt findet man ja noch 'nen netten Comic zu aktualisierungen o.ä. :))

**Comment by joker234** [comment]
Will @derkleineMo sich vielleicht auch dazu äußern? Vielleicht hat der ja eine gute Idee :)

**Comment by koebi** [comment]
Vorschlag: Vorkurs-Pläne rausnehmen und durch einen großen Link ersetzen!

**Comment by joker234** [comment]
Go for it

**Comment by koebi** [comment]
'nen QR-Code wär sicher auch cool :)

**Comment by joker234** [comment]
wer auch immer das macht kann z.B. das hier verwenden:

    apt-get install qrencode
    qrencode -s 7 -o file.png "mathphys.info/vorkurs/plan"

**Comment by derkleineMo** [comment]
Das LaTeX-Paket `qrcode` leistet da ganz großartige Dienste:

    \usepackage{qrcode}
    ...
    \qrcode[height=4cm]{http://mathphys.info/vorkurs/plan}
