### ISSUE TITLE
Profs der Ersti-Vorlesungen vorstellen

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#233]
Es wäre vielleicht ganz nett, wenn man die Profs, die die Ersti-Vorlesungen halten, kurz vorstellt, also z. B. mit Bild / jeweiligem Forschungsgebiet / kurzem Interview / ...
Wie fändet ihr das?

**Comment by flugdrachen** [comment]
Ex 1, Theo 1, IPI, Ana1, LA1, MafIn, Technische Info, Programmierkurs (alle?)

**Comment by TomTomRixRix** [comment]
Diese Vorstellungen müsste man jedes Jahr aktualisieren, was einen erheblichen Aufwand darstellt. Wenn es nur kurze Steckbriefe sind mit Namen, Arbeitsgruppe/Forschungsgebiet, Name der Erstivorlesung und einem Bild, dann wäre das vielleicht noch umsetzbar, aber dann ist der Mehrwert auch nicht so groß.

Ich denke, dass es im Vorkurs deutlich bessere Gelegenheiten, die Dozentinnen der Erstsemestervorlesungen kennenzulernen, zum Beispiel der Who-is-Who Vortrag und das Dozentinnnencafé. Außerdem fände ich es cool, interaktive videobasierte Formate auf Social Media Seiten oder unserer Website den Erstis zur Verfügung zu stellen. Dies geht jedoch leider nicht in einem gedruckten Ersti-Info.
