### ISSUE TITLE
Erneuern des Abschnitts "Alles verändert sich, wenn ihr es verändert"

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhys/Ersti-Info#236]
Im ordner `mathphys/fachschaft.tex` müsste der oben genannte Abschnitt erneuert werden, da er tw veraltete Informationen enthält

**Comment by TomTomRixRix** [comment]
Ist dieses Issue noch aktuell oder wurden die Informationen schon aktualisiert? Falls es noch etwas zu aktualisieren gibt, bitte direkt tun oder hier angeben, welche Infos aktualisiert werden müssen.

**Comment by TomTomRixRix** [comment]
Mir sind folgende Punkte aufgefallen, die man aktualisieren sollte:
* Skripte werden zwar noch von uns gedruckt und ausgegeben, aber nicht mehr aus QSM bezahlt
* Der MathPhysTheo Absatz ist leider auch nicht mehr ganz passend, aber den FSWE teil, sollte man drin lassen. Vielleicht kann man einen Absatz zum Naturwissenschaftsball hinzufügen?
