### ISSUE TITLE
Verantwortliche im Sinne des Presserechtes

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/Ersti-Info#238]
Aktuell scheint _die Fachschaft_ Verantwortliche im Sinne des Presserechtes zu sein. Wir müssen mal darüber diskutieren, wen wir in Zukunft dort hin schreiben, da es laut Personen, die im FS Raum sitzen, eine natürliche Person sein muss. Falls es auch eine juristische Person seien kann, muss das die VS sein.

**Comment by koebi** [comment]
Zu allererst: Ich bin kein Anwalt. Ich habe formal keine Ahnung. 

Ich hab allerdings gerade mal ein bisschen Presserecht gelesen. Da steht folgendes drin:
(Impressum)[http://www.landesrecht-bw.de/jportal/?quelle=jlink&query=PresseG+BW+%C2%A7+8&psml=bsbawueprod.psml&max=true] - Auf jedem Druckwerk […] müssen Name oder Firma und Anschrift des […] Herausgebers genannt sein.

Weiterhin steht hier:
Auf den periodischen Druckwerken sind ferner Name und Anschrift des verantwortlichen Redakteurs anzugeben. 

Gucken wir kurz nach, was periodische Druckwerke sind, stellen wir recht fix fest, dass das Ersti-Info da nicht zugehört, da es nicht ("im Abstand von nicht mehr als sechs Monaten")[http://www.landesrecht-bw.de/jportal/?quelle=jlink&query=PresseG+BW+%C2%A7+7&psml=bsbawueprod.psml&max=true] erscheint, sondern ein mal pro Jahr :)

Dementsprechend brauchen wir meiner Ansicht nach keinen V.i.S.d.P (denn das ist glaube ich der verantwortliche Redakteur), sondern müssen nur den Herausgeber kennzeichnen.

Aus meiner Sicht ist das die Fachschaft MathPhysInfo mit genannter Anschrift. Nicht die VS, auch nicht eine natürliche Person (vgl. "Firma" in den Bestimmungen zum Impressum), sondern eben die Fachschaft!

Aktuell steht da allerdings nur "Fachschaft", da könnte man durchaus mal "Fachschaft MathPhysInfo" draus machen ;)

**Comment by TomTomRixRix** [comment]
Ich habe auch keine Ahnung und müsste das erst recherchieren. Eigentlich wollte ich auch nur die Diskussion anregen, weil uns das gerade aufgefallen ist. 

Wer kann den offiziell Herausgeber sein? Muss das nicht auch eine natürliche oder juristische Person sein, weshalb die Fachschaft MathPhysInfo nicht in Frage kommt? Vielleicht geht es, wenn man eine unserer Studienfachschaften als Herausgeber nimmt.

**Comment by koebi** [comment]
Mir scheint, dass der Begriff des "Herausgebers" presserechtlich nicht so klar definiert ist.
Ich persönlich würde den oben schon zitierten Abschnitt, und insbesondere den Teil mit "oder Firma" als genug Grund ansehen, um da mit gutem Gewissen auch juristische Personen hinzuschreiben.

Weiterhin ist (aus meiner Sicht) die Fachschaft MathPhysInfo als "Zusammenschluss" der Studienfachschaften Mathematik, Physik und Informatik juristische Person genug als dass ich das gerechtfertigt genug finde, da "Fachschaft MathPhysInfo" hinzuschreiben. 

Aus meiner Sicht ist nämlich genau das der Herausgeber, nicht einzelne Studienfachschaften, nicht die VS, nicht einzelne Personen, sondern genau dieser Zusammenschluss. 

Ich glaube auch wirklich nicht, dass wir uns aus irgendeinem Grund hier Gedanken machen müssen. Wenn irgendjemand findet, dass sich die Fachschaft immer penibel an alle Gesetze halten muss, soll er bitte wo anders anfangen als im Impressum des Ersti-Info, oder die Fachschaft verklagen ;)

**Comment by OccamsBeard** [comment]
*Ausführlich*

Herausgeberin
Fachschaft MathPhysInfo

Kooperation der Studienfachschaften
Mathematik, Physik und Informatik
an der Universität Heidelberg

Im Neuenheimer Feld 205 (Mathematikon)
Raum 1.301
69120 Heidelberg

Die Fachschaften Mathematik, Physik und Informatik
sind Teil einer Körperschaft des öffentlichen Rechts,
gesetzl. vertr. durch den
Vorsitz der Verfassten Studierendenschaft
Albert-Überle-Str. 3-5
69120 Heidelberg

Website: https://www.stura.uni-heidelberg.de/impressum

*Kurz*
FS MathPhysInfo, vertr. durch die Vorsitzenden d. Verfassten Studierendenschaft, Julia Patzelt und David Kelly Hawes, Albert-Überle-Str. 3-5, 69120 Heidelberg

**Comment by OccamsBeard** [comment]
### Aktualisiert:

       Herausgeberin: & Fachschaft MathPhysInfo\\
        & Im Neuenheimer Feld 205, Raum 1.301\\
        & 69120 Heidelberg\\
        & www.mathphys.info\\
        & vertr. durch den Vorsitz der\\
        & Verfassten Studierendenschaft\\
        & \vorsitzVS\\
        & Albert-Überle-Straße 3-5\\
        & 69120 Heidelberg
