### ISSUE TITLE
zu Aktualisierendes

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#241]
Die Informationen im zu aktualisieren Dokument sollten aktualisiert werden.

**Comment by flugdrachen** [comment]
@imntl was war da nochmal letztes Jahr mit den Bildern von den (Studien-)Dekanen das nur du machen konntest? Willst du mir einfach sagen worauf ich bei Farbprofil/Auflösung achten soll?

**Comment by TheEbolaDoc** [comment]
fixed in 8fe67d13c00a63746370fa4acc7e9c2e6bcd5338
