### ISSUE TITLE
Zweispaltig und Layout/Design

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/Ersti-Info#242]
Der Text soll auf zweispaltig geändert werden.

Das Design und das Layout sollen angepasst werden.

Ziel insgesamt: Etwas Platz und somit Seiten sparen.

**Comment by flugdrachen** [comment]
Wenn wir ein Angebot von der Druckerei einholen wollen, brauchen wir eine ungefähre Abschätzung für die Seitenzahl, d. h. Es wäre gut, wenn wir in spätestens 2 Wochen feststellen können, ob und in welchem Umfang wir durch eine Layoutänderung Seiten sparen können.

**Comment by TomTomRixRix** [comment]
Aktuell sidn es 67 Seiten. Wenn die Texte fertig sind, müssen die Bilder noch an die entsprechenden Positionen gepackt werden, das hängt aber von der Länge der Texte und deren Reihenfolge ab.

Dabei kann man dann auch #37 berücksichtigen.
