### ISSUE TITLE
Cover / Titelbild

### ISSUE THREAD

**Issue by TheresaKaiser** [FachschaftMathPhys/Ersti-Info#245]
Vorschläge/Entwürfe/Ideen sind gerne gesehen :)

**Comment by TomTomRixRix** [comment]
Ideen so far:
* [Where's Waldo?](https://en.wikipedia.org/wiki/Where%27s_Wally%3F) Wimmelbild. Als Hintergrund kann man ganz viele gleich aussehende Studis nehmen, die auf dem Exerzierplatz stehen, vielleicht mit dem KIP oder dem Theoretikum im Hintergrund.
* Angry Bilds mit den Ersti Vorlesungen (Ex,Theo, LA, Ana, IPI) als Vögel und Profs als Schweinchen?

**Comment by flugdrachen** [comment]
Neuester Plan: Munchkin-Karte.
Eine Zeichnung ist in Arbeit.
