### ISSUE TITLE
Datum fürs FSWE

### ISSUE THREAD

**Issue by TheEbolaDoc** [FachschaftMathPhys/Ersti-Info#255]
in der Datei `./zu_aktualisieren/daten.tex` sollte noch das Datum des FSWE im WS 18/19 angepasst werden! :blush:

**Comment by TomTomRixRix** [comment]
Dieses Datum wird anscheinend nicht mehr verwendet im Ersti-Info uns kann somit auch als Variabel entfernt werden. Sobald man es wieder benötigt, kann man sie ja wieder anlegen. Aber das ist nicht realistisch, oder @jgraefje ?

**Comment by jgraefje** [comment]
Ich denke nicht, dass das wieder benötigt werden wird.
Die Anmeldugns-Liste zum FSWE hängt ja auch bewusst nicht außen am FS-Raum und wer nicht auf anderem Wege erfahren hat, wann das FSWE stattfindet, hat wahrscheinlich auch keinen so drängenden Grund dabei zu sein.
