### ISSUE TITLE
Überschriften / Sections und Subsections

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/Ersti-Info#263]
Mit dem neuen Layout sieht man einen deutlichen Unterschied zwischen Sections und Subsections.
Wir sollten alles durchgehen und entscheiden, was eine Section/Subsection ist, so dass das inhaltlich Sinn ergibt.
In dem Zuge sollten wir auch Überschriften verkürzen, damit sie möglichst nicht über zwei Zeilen gehen.
Insbesondere sollten bei den Studiengangsbeschreibungen das "Bachelor" gestrichen werden, weil das eigentlich klar ist. 
Vorschlag für neues Format: {Mathematik, Physik, Angewandte Informatik} {50%,100%}

**Comment by TomTomRixRix** [comment]
Falls die Überschriften sich nicht kürzen lassen, sollte wenigstens der Zeilenumbruch mit `\\` ordentlich gemacht werden, damit der Blocksatz die Wörter nicht komplett auseinander zieht, sondern einfach in der nächsten Zeile linksbündig weiter schreibt
