### ISSUE TITLE
Festplakat für die Rückseite

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/Ersti-Info#286]
Auf die Rückseite soll wieder das MathPhysTheo Plakat. Dafür bräuchten wir zwei Versionen des Plakats als PDF-Dateien:
1. mit der Größe `216 x 303 mm` für die gedruckte Version, wo auf jeder der vier Seiten bis zu 3 mm abgeschnitten werden können, ohne dass es stört. Die 3 mm Beschnittzugabe sollten aber am besten einfach den Farbverlauf weiterführen.
2. mit der Größe `210 x 297 mm`  für die digitale Version

**Comment by flugdrachen** [comment]
Wahrscheinlich wird diesmal kein Festplakat auf der Rückseite landen, sondern eine zum Cover passende eigens gestaltete Anno 1800-Rückseite
