### ISSUE TITLE
Titelbild

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/Ersti-Info#287]
## _Hier wird noch eine Idee gesucht!_

Früher hatten die Coverbilder immer was mit Labyrinthen (weil man am Anfang so verwirrt ist an der Uni), danach mit nerdigen (Computer-)Spielen zu tun. Diese Tradition können man weiterführen. Aktuell gibt es die folgenden Ideen:

1.  [Where's Waldo? ](https://en.wikipedia.org/wiki/Where%27s_Wally%3F) Wimmelbild. Als Hintergrund kann man ganz viele gleich aussehende Studis nehmen, die auf dem Exerzierplatz stehen, vielleicht mit dem KIP oder dem Theoretikum oder dem neuen Hörsaal und Lernzentrum im Hintergrund.
2. Angry Bilds mit den Ersti Vorlesungen (Ex,Theo, LA, Ana, IPI) als Vögel und Profs als Schweinchen?
3. Die verrückte Universität: In Anlehnung an das Brett-Spiel, das verrückte Labyrinth
4. eine Pokemon-Karte mit Super-Special-Effects, ähnlich wie die Munchkin Karte

Auf der Titelseite sollten folgende Elemente vorhanden sein:
* Titel: Ersti-Info
* Fachschaft MathPhysInfo oder einfach μφι
* ggf. das aktuelle Jahr
* ggf. Anspielungen an 180 CP, Mathe Physik Info, andere studiumsbezogene Anspielugen

**Comment by TomTomRixRix** [comment]
Die neuste Idee ist es, ein [Festplakatdesign](https://mathphys.fsk.uni-heidelberg.de/~juliana/plakate_ws1920/photo_2019-07-06_00-26-52.jpg) als Cover zu nehmen

**Comment by flugdrachen** [comment]
Aktueller Stand ist, ein Cover im Stil von Anno 1800 zu verwenden und somit dem Computerspiel-Thema wieder treu zu bleiben
