### ISSUE TITLE
AP FP aus der Informatik

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#29]
Im Erstiinfo werden AP und FP aus der Physik erwähnt. Man sollte auch mal was über Informatik-AP und  -FP schreiben.

**Comment by joker234** [comment]
das passiert hoffentlich in der fachlichen Überarbeitung @friedz @SinForest

**Comment by friedz** [comment]
**Proseminar** und **Seminar** könnten/sollten bei der Gelegenheit vermutlich auch angesprochen werden

**Comment by friedz** [comment]
also ich hab jetzt was dazu geschrieben aber ich finden den Text von mir nicht so geil
will das mal von @SinForest oder @joker234 durchgeschaut und vielleicht verbessert werden
