### ISSUE TITLE
Eval veröffentlicht?

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#30]
Im Erstiinfo steht, dass wir die (Physik-)Eval veröffentlichen. Entspricht das noch der Realität oder will man das Detail lieber weg lassen?

**Comment by koebi** [comment]
Ja, man findet Evalergebnisse immer noch vor dem FS-Raum, wenn der Prof sein Einverständnis gegeben hat.

**Comment by joker234** [comment]
findet man? Ich finde die letzten beiden zumindest nicht. Man könnte zumindest den Satz https://github.com/FachschaftMathPhys/Ersti-Info/blob/5e1bbd0888512c7a128424d98dbe2fe1e8416bf8/mathphys/evaluation.tex#L23-L28 entfernen.

**Comment by joker234** [comment]
immer noch aktuell und sollte dieses Jahr überarbeitet werden.

**Comment by friedz** [comment]
der Ort
```LaTeX
z.B. vor dem Fachschaftsraum (im Infoständer links der Tür)
```
sollte noch auf die aktuelle Situation angepasst werden
