### ISSUE TITLE
Bafög-Artikel 

### ISSUE THREAD

**Issue by mathivierpunktnull** [FachschaftMathPhys/Ersti-Info#311]
Die Förderungsbeträge haben sich geändert. Ebenfalls sollten die Öffungszeiten des Bafögs angepasst (oder weggelassen) werden.

**Comment by TomTomRixRix** [comment]
Meines Wissens geben wir nur noch den BAföG Höchstsatz an, den ich mit commit 48a10e2cf2654afb8143325f02b62505b8828fdc in die zu aktualisierenden Daten ausgelagert habe und den neuen Wert eingefügt habe. 

Die Öffnungszeiten sind jetzt ebenfalls nicht mehr hartgecodet, sondern mit einem Verweis auf die entsprechende Website.

Falls sonst noch irgendwas unklar sein sollte, bitte konkrete Zeilen oder Textpassagen angeben, bei denen etwas verändert werden muss, ansonsten müsste das Issue fertig bearbeitet sein.
