### ISSUE TITLE
Aktuelle Entwicklungen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/Ersti-Info#331]
Zusätzlich zu den Informationen, die jedes Semester zu aktualisieren sind (#241), müssen auch noch Änderungen durchgeführt werden, die einmalig sind. Mir fallen momentan folgende Punkte ein:
* Die Halle 02 hat wegen der Coronapandemie ihr Konzept geändert und muss deshalb aus der Liste der Bars, Clubs und Diskotheken genommen werden. Man sollte die anderen Locations auch einmal durchgehen und überprüfen, ob sie noch existieren.
* Im kommenden Wintersemester wird es eine Probephase für eine Theaterflatrate geben. Dies sollte bei den Kulturangeboten im Ersti-Info beworben werden.

**Comment by TomTomRixRix** [comment]
Anfifte

**Comment by TomTomRixRix** [comment]
Vorkurs allgemein anpassen

**Comment by itsraeesa** [comment]
Verschiedene Texte wurden angepasst
- bekannte digitale Optionen wurden hinzugefuegt
- Bars und Kneipen wurden aktualisiert
- Angebote aktualisiert

**Comment by TomTomRixRix** [comment]
Mit #344 behoben
