### ISSUE TITLE
mehr XKCD

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#37]
Man könnte mehr XKCD (oder andere passende Comics) ins Ersti-Info packen. Wenn ich das mit anderen Ersti-Heften verglichen habe ist unseres erstaunlich Comic-arm.

**Comment by SinForest** [comment]
Dieser XKCD passt z.B. viel besser zu "Wohnen in Heidelberg":
http://xkcd.com/1715/

**Comment by friedz** [comment]
dieser XKCD wär ziemlich gut neben dem Bachelor Info Artikel
![Backups](http://imgs.xkcd.com/comics/backups.png)

**Comment by imntl** [comment]
Wenn noch jemand coole XKCDs kennt oder findet, die ins Ersti-Info passen, oder andere coole Comics, die wir auch verwenden dürfen, könnt ihr gerne weiter posten. Ich werde das langsam mal angehen und versuchen, noch weitere zu finden.

**Comment by friedz** [comment]
![Black Hole](http://xkcd.com/1680/) ist auch ziemlich gut und passt sicher irgendwo dazu
![Black Hole](http://imgs.xkcd.com/comics/black_hole.png)

**Comment by joker234** [comment]
@imntl magst du für den nächsten Release schon ein paar neue umsetzen?

**Comment by imntl** [comment]
Ein paar sind schon eingefügt, ein paar kommen noch.

**Comment by imntl** [comment]
Ich hab jetzt noch ein paar XKCDs eingefügt. Allerdings sind noch einige Seiten leer und es können bestimmt auch teilweise besser passende Comics eingefügt werden. Für einen Start ist es aber meiner Meinung nach gar nicht so schlecht.
Das Issue kann aber ruhig offen bleiben, damit wir wissen, dass wir immer noch mehr XKCDs und andere coole Comics in das Ersti-Info bringen können.

**Comment by joker234** [comment]
argh, schreib doch nicht „fixes #37 ...“ in den PR :P

**Comment by imntl** [comment]
![](https://imgs.xkcd.com/comics/computer_problems.png)

**Comment by friedz** [comment]
![](https://imgs.xkcd.com/comics/computers_vs_humans.png)
