### ISSUE TITLE
Liste von Beratungsangeboten für behinderte Studierende

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Ersti-Info#39]
Siehe auch Reso der ZaPF

**Comment by joker234** [comment]
Details?

**Comment by joker234** [comment]
Ich finde ja dass ein Link auf das Dschungelbuch an geeigneter Stelle ausreicht.

**Comment by koebi** [comment]
Jup, das sollte ausreichen. Der entsprechende Link wäre https://dschungelbuch.stura.uni-heidelberg.de/index.php/Behinderte_studieren, mir ist nur noch nicht ganz klar, wo er hin sollte…

**Comment by friedz** [comment]
entweder irgendwie in den Dunstkreis von **Nightline** und ähnlichem oder unter **An der Uni...**

wobei eine eigene subsection sicher zu viel wäre wenn es nur ein Link sein soll und es so in keine der existierenden Teile passt
