### ISSUE TITLE
Artikel über das Mathematikon

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#44]
soll im Ersti-Info ein Artikel über das Mathematikon stehen? Wäre vielleicht ganz nützlich aber nicht unbedingt nötig. Meinungen?

**Comment by koebi** [comment]
Ich bin eher dagegen. Wir erwähnen keines der anderen Gebäude explizit, was im Glossar steht ist meiner Meinung nach ausreichend (oder ausreichend zu machen ;) ).  Mir ist auch nicht ganz klar, was da so drin stehen soll, was für Erstis relevant ist. Bedenke, für neue Studis ist das Mathematikon der Normalzustand.

**Comment by joker234** [comment]
good point
