### ISSUE TITLE
Straßenbahn im Feld aktualisieren

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#45]
hopo/ueberblick_gremien.tex:47

**Comment by imntl** [comment]
hopo/ueberblick_gremien.tex ist gar nicht in der Endversion drin, sondern im Moment tatsächlich ueberblick_gremien_2014.

**Comment by joker234** [comment]
trotzdem sollte ein Artikel über die Straßenbahn im Feld drin stehen. Ist immerhin ein sehr aktuelles Thema.

**Comment by imntl** [comment]
Sollte vielleicht ein eigener Pull Request werden, da der HoPo Pull Request jetzt schon unübersichtlich ist.
