### ISSUE TITLE
Caféte aktuell?

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#46]
Im Artikel mathphys/fachschaft.tex steht dieser Absatz. Stimmt dieser noch?

> Am Philweg gibts außerdem die Caféte. Dies ist ein altes Gartenhäuschen im Philosophenweg 12, das wir im Sommer 2009 liebevoll renoviert und 2013 wieder nutzbargemacht zu haben. Neben Sofas und Tischchen stehen auch Kaffeemaschine, Wasserkocher und Tassen drin. Kaffee und Tee gibt es zum Selbstkostenpreis und ab und zu stehen auch Kekse oder Gummibärchen da.

**Comment by koebi** [comment]
Ja, generell stimmt der noch. Kleinigkeiten könnte man aber (an dem gesamten Artikel) verändern.

**Comment by joker234** [comment]
So weit ich gehört hab ist die Cafete nie offen zur Zeit.

**Comment by imntl** [comment]
Also die Cafete ist im Moment wahrscheinlich nur offen, wenn gerade auch StuRa ist. Also nie ist ja auch falsch.

**Comment by joker234** [comment]
Nie für Studis.

**Comment by friedz** [comment]
Wenn wir die Cafete drin lassen sollten wir die Cafeten Fete erwähnen den die ist doch halbwegs regelmäßig

Und ich würde dafür plädieren sie drin zu lassen und dazu schreiben das sie zur zeit leider eher selten offen ist
