### ISSUE TITLE
Lizenzen auf der Karte

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#55]
Die OSM Lizenz steht derzeit (v2015 web) im Mantelbogen und auf der Karte nicht ganz richtig. Bei der Web Version würde ich das auf jeden Fall nach der OSM Konvention machen. Siehe: http://wiki.openstreetmap.org/wiki/Legal_FAQ#3._Using

Außerdem würde ich diese Seite verlinken: http://www.openstreetmap.org/copyright

**Comment by joker234** [comment]
@koebi gibt's nen Grund warum das nicht einfach so realisiert wie sich das OSM wünscht? (vgl. Link von mir). Imho könnte man in der Webversion auch auf den zweiten Link verlinken, ist aber nicht zwingend nötig.

**Comment by koebi** [comment]
Ich hatte versucht, das mit meiner Änderung so gut wie möglich umzusetzen, mir ist aber um ehrlich zu sein nicht so ganz klar, wie OSM das möchte. Im Impressum vorne sind die Änderungen aus Konsistenzgründen recht minimal gehalten - setzen aber meiner Meinung nach das recht gut um…
