### ISSUE TITLE
Zeilenabstände falsch in EDV

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/Ersti-Info#8]
in EDV → LSF → zweiter Absatz sind die Zeilenabstände zu groß. Siehe auch https://mathphys.fsk.uni-heidelberg.de/w/wp-content/uploads/erstiinfo_2014.pdf Seite 41.

vgl. #7

**Comment by joker234** [comment]
\o/

**Comment by joker234** [comment]
Z.B. auf Seite 48 noch

**Comment by koebi** [comment]
Scheint sich erledigt zu haben, ich finde zumindest in der aktuellen vorschau_inhalt nix.
